language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: precise

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2

android:
  components:
    # tools required
    - tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-28
    - android-22

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - mv app/dummy-google-services.json app/google-services.json
  - ls -la
  # Enable the line below once we get all the test passing, currently most of the tests are failing
  # so we'll just if the project compiles
  #Run All tests Unit and Instrumentation

  # Make sure that even the sample module builds OK
  - travis_wait ./gradlew build --stacktrace
  #- travis_wait ./gradlew :app:jacocoTestReport
  #- travis_wait ./gradlew :p2p-sync:coveralls